name: Daily Menu

on:
    schedule:
        - cron: "17 8 * * 1-5"
          timezone: "Asia/Seoul"
        - cron: "17 8 * * 1"
          timezone: "Asia/Seoul"
    workflow_dispatch:

jobs:
    send-daily-menu:
        if: github.event.schedule == '17 8 * * 1-5'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run daily menu bot
              env:
                  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  BABFULL_MENU_URL: ${{ secrets.BABFULL_MENU_URL }}
              run: python menu_bot.py

    send-weekly-menu:
        if: github.event.schedule == '17 8 * * 1'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run weekly menu image bot
              env:
                  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  BABFULL_MENU_URL: ${{ secrets.BABFULL_MENU_URL }}
              run: python sikdan_image.py
